# This is a basic workflow to help you get started with Actions

name: Testing out Github Actions

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Create a seperate check with the information
      - name: Create check run
        id: create_check
        uses: octokit/request-action@v2.x
        with:
          route: POST /repos/eshan-trehan/action-test-repository/check-runs
          mediaType: '{"previews": ["antiope"]}'
          owner: ${{ github.repository_owner }}
          repo: ${{ github.event.repository.name }}
          name: My check run
          head_sha: ${{ github.event.pull_request.head.sha }}
          status: in_progress
          output: '{"title":"Check run from actions","summary":"Summary of the check run","text":"details"}'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
