name: Action Test Workflow

on:
  push:
    branches:
      - 'main'
  pull_request:
    branches:
      - 'main'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Run tests
      run: |
        echo "Running tests..."
        # Run your test command here

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Run deployment script
      run: |
        echo "Running deployment script..."
        # Run your deployment command here
    
    - name: Check step 2
      id: step2
      uses: actions/github-script@v3
      with:
        script: |
          // This is a JavaScript code
          const time = new Date().toISOString()
          await github.checks.create({
            owner: context.repo.owner,
            repo: context.repo.repo,
            name: 'My Custom Check',
            head_sha: github.context.sha,
            status: 'completed',
            conclusion: 'success', // can be 'success', 'failure', 'neutral', etc.
            started_at: time,
            completed_at: time,
            output: {
              title: 'My Custom Check',
              summary: 'This is an example of creating a custom check for an individual step'
            }
          })
