name: Action Test Workflow

on:
  push:
    branches:
      - 'main'
  pull_request:
    branches:
      - 'main'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Run tests
      run: |
        echo "Running tests..."
        # Run your test command here

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Run deployment script
      run: |
        echo "Running deployment script..."
        # Run your deployment command here
    
    - name: Custom GitHub Check
      id: check
      uses: actions/github-script@v4
      with:
        script: |  
          // JavaScript code
          const sha = context.payload.after || context.sha;
          const check = await github.rest.checks.create({
            owner: context.repo.owner,
            repo: context.repo.repo,
            name: 'My Custom Check',
            head_sha: sha,
            status: 'completed',
            conclusion: 'success',
            output: {
              title: 'My Custom Check',
              summary: 'This is an example of creating a custom check for an individual step',
            },
          });
