name: Slash Command
on:
  issue_comment:
    types: [created]
  repository_dispatch:
    types: [dismiss-command]
jobs:
  slash_command_dispatch:
    if: github.event_name == 'issue_comment' && github.event.issue.pull_request && github.event.action == 'created'
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Slash Command Dispatch
        uses: peter-evans/slash-command-dispatch@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          config: >
            [
              {
                "command": "dismiss",
                "permission": "none",
                "issue-type": "pull-request"
              }
            ]
  execute_dismiss_command:
    if: github.event_name == 'repository_dispatch' && github.event.action == 'dismiss-command'
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Export Pull Request Identifier
        run: |
          REPO_FULL_NAME=${{ github.event.client_payload.github.payload.repository.full_name }}
          ISSUE_NUMBER=${{ github.event.client_payload.github.payload.issue.number }}
          echo "PULL_REQUEST_IDENTIFIER=${REPO_FULL_NAME}/${ISSUE_NUMBER}" >> $GITHUB_ENV
      - name: Print Pull Request Identifier
        run: echo "$PULL_REQUEST_IDENTIFIER"
      - name: Echo Slash Command Arguments
        run: echo "${{ toJson(github.event.client_payload.slash_command.args) }}"
      - name: Add reaction
        uses: peter-evans/create-or-update-comment@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          repository: ${{ github.event.client_payload.github.payload.repository.full_name }}
          comment-id: ${{ github.event.client_payload.github.payload.comment.id }}
          reactions: hooray
