name: Slash Commands

on:
  issue_comment:
    type:
      - created
jobs:
  dispatch:
    if: |
      github.event_name == 'issue_comment'
    runs-on: ubuntu-latest
    permissions:
      checks: write
      contents: read
    steps:
      - name: Run a one-line script
        run: echo Hello, world!

