name: Slash Commands

on:
  issue_comment:
    type:
      - created
jobs:
  dispatch:
    if: github.event_name == 'issue_comment'
    runs-on: ubuntu-latest
    steps:
      - name: Slash Command Dispatch
        uses: peter-evans/slash-command-dispatch@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          dispatch_type: workflow
          issue_type: pull-request
          commands: |
            dismiss
