name: Slash Commands

on:
  issue_comment:
    type:
      - created

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      checks: write
      contents: read
    steps:
      - name: Run a one-line script
        run: echo Hello, world!

