name: Slash Commands

on:
  issue_comment:
    type:
      - created
jobs:
  dispatch:
    if: github.event_name == 'issue_comment'
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - name: Slash Command Dispatch
        uses: peter-evans/slash-command-dispatch@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          dispatch-type: workflow
          issue-type: pull-request
          commands: |
            dismiss

