name: Slash Command
on:
  issue_comment:
    types: [created]

jobs:
  handle-slash-command:
     # The type of runner that the job will run on
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      # Initialize the SHOULD_CONTINUE environment variable
      - name: Initialize SHOULD_CONTINUE
        run: echo "SHOULD_CONTINUE=true" >> $GITHUB_ENV

      # Check if the comment starts with a Slash
      - name: Check if the comment starts with a Slash
        uses: actions/github-script@v6
        with:
          script: |
            // Get the comment ID from the event payload
            if (!context.payload.comment.body.startsWith('/')) {
              console.log('The comment does not start with a slash. Exiting.');
              
              // Set the environment variable SHOULD_CONTINUE to false
              const fs = require('fs');
              fs.appendFileSync(process.env.GITHUB_ENV, 'SHOULD_CONTINUE=false\n');
            } else {
              console.log('The comment starts with a slash.');

              // Add a reaction to the issue comment indicating 
              // that the command was received.
              await github.rest.reactions.createForIssueComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                comment_id: context.payload.comment.id,
                content: 'eyes',
              });
            }
    
      # Check out the repository's code
      - name: Checkout repository
        if: env.SHOULD_CONTINUE == 'true'
        uses: actions/checkout@v3

      # Set up Python
      - name: Set up Python
        if: env.SHOULD_CONTINUE == 'true'
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      # Install Python Packages
      - name: Install dependencies
        if: env.SHOULD_CONTINUE == 'true'
        working-directory: ./lab/github_slash_command
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt

      # Run Python Script
      - name: Run Python Script
        if: env.SHOULD_CONTINUE == 'true'
        working-directory: ./lab/github_slash_command
        run: python3 main.py
        env:
          OWNER: ${{ github.event.repository.owner.login }}
          REPO: ${{ github.event.repository.name }}
          PULL_REQUEST_NUMBER: ${{ github.event.issue.number }}
          ISSUE_COMMENT_ID: ${{ github.event.comment.id }}
          ISSUE_COMMENT_BODY: ${{ github.event.comment.body }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
